import 'global.dart';

String loginString = lang == 'vi' ? 'Đăng nhập' : 'Sign In';
String signUpString = lang == 'vi' ? 'Đăng ký' : 'Sign Up';
String emailString = 'Email';
String passwordString = lang == 'vi' ? 'Mật khẩu' : 'Password';
String forgetPasswordString = lang == 'vi' ? 'Quên mật khẩu?' : 'Forgot Password?';
String forgotPasswordString = lang == 'vi' ? 'Quên mật khẩu' : 'Forgot Password';
String notHaveAccountString = lang == 'vi' ? 'Chưa có tài khoản?' : 'Don\'t have account';
String registerNowString = lang == 'vi' ? 'Đăng ký ngay' : 'Register now';
String createAccountString = lang =='vi' ? 'Tạo tài khoản' : 'Create Account';
String infoAccountString = lang =='vi' ? 'Thông tin tài khoản' : 'Account Information';
String infoPersonalString = lang =='vi' ? 'Thông tin cá nhân' : 'Personal Information';
String confirmPasswordString = lang == 'vi' ? 'Xác nhận mật khẩu' : 'Confirm Password';
String nextString = lang == 'vi' ? 'Tiếp' : 'Next';
String alreadyHaveAccount = lang == 'vi' ? 'Đã có tài khoản?' : 'Already have account?';
String fullNameString = lang == 'vi' ? 'Họ và Tên' : 'Fullname';
String studentIdString = lang == 'vi' ? 'Mã sinh viên' : 'Student ID';
String classString = lang == 'vi' ? 'Lớp' : 'Class';
String facultyString = lang == 'vi' ? 'Khoa' : 'Faculty';
String enterEmailString = lang == 'vi' ? 'Nhập email của bạn' : 'Enter your email address';
String orString = lang == 'vi' ? 'hoặc' : 'or';
String backToSignInString = lang == 'vi' ? 'Quay về đăng nhập' : 'Back to Sign In';
String sendToEmailString = lang == 'vi' ? 'Gửi tới Email' : 'Send to Email';
String homeString = lang == 'vi' ? 'Trang chủ' : 'Home';
String scheduleString = lang == 'vi' ? 'Lập lịch' : 'Schedule';
String notificationString = lang == 'vi' ? 'Thông báo' : 'Notifications';
String meString = lang == 'vi' ? 'Tôi' : 'Me';
String trainingProgramString = lang == 'vi' ? 'Chương trình đào tạo' : 'Training Programmes';
String recentModuleString = lang == 'vi' ? 'Học phần gần đây' : 'Recent Modules';
String studyProcessString = lang == 'vi' ? 'Tiến trình học tập' : 'Study Process';
String internString = lang == 'vi' ? 'Thực tập' : 'Intern';
String postString = lang == 'vi' ? 'Bài đăng' : 'Post';
String allString = lang == 'vi' ? 'Tất cả' : 'All';
String schoolFacultyString = lang == 'vi' ? 'Trường/ Khoa' : 'School/Faculty';
String companyString = lang == 'vi' ? 'Công ty' : 'Company';
String statisticString = lang == 'vi' ? 'Thống kê' : 'Statistic';
String listPartnerString = lang == 'vi' ? 'DS Đối tác' : 'Partner List';
String reportString = lang == 'vi' ? 'Báo cáo' : 'Report';
String searchString = lang == 'vi' ? 'Tìm kiếm' : 'Search';
String cancelString = lang == 'vi' ? 'Huỷ bỏ' : 'Cancel';
String recentString = lang == 'vi' ? 'Gần đây' : 'Recent';
String shortTrainingProgramString = lang == 'vi' ? 'CTDT' : 'Program';
String moduleString = lang == 'vi' ? 'Học phần' : 'Module';
String lecturerString = lang == 'vi' ? 'Giảng viên' : 'Lecturer';
String partnerString = lang == 'vi' ? 'Đối tác' : 'Partner';
String myProfileString = lang == 'vi' ? 'Hồ sơ cá nhân' : 'My Profile';
String settingString = lang == 'vi' ? 'Cài đặt' : 'Settings';
String shortStudentIdString = lang == 'vi' ? 'MSV' : 'Student ID';
String myCVString = lang == 'vi' ? 'CV của tôi' : 'My CV';
String changePasswordString = lang == 'vi' ? 'Thay đổi mật khẩu' : 'Change Password';
String logOutString = lang == 'vi' ? 'Đăng xuất' : 'Sign Out';
String editProfileString = lang == 'vi' ? 'Chỉnh sửa hồ sơ' : 'Edit Profile';
String dateOfBirthString = lang == 'vi' ? 'Ngày sinh' : 'Birthday';
String languageString = lang == 'vi' ? 'Ngôn ngữ' : 'Language';
String vietnameseString = lang == 'vi' ? 'Tiếng Việt' : 'Vietnamese';
String englishString = lang == 'vi' ? 'Tiếng Anh' : 'English';
String darkModeString = lang == 'vi' ? 'Chế độ tối' : 'Dark Mode';
String onString = lang == 'vi' ? 'Bật' : 'On';
String offString = lang == 'vi' ? 'Tắt' : 'Off';
String doNotDisturbString = lang == 'vi' ? 'Không làm phiền' : 'Do not disturb';
String soundString = lang == 'vi' ? 'Âm báo' : 'Sound';

List<String> classDropDownString = ['K64C-CLC', 'K64C-B'];
List<String> facultyDropDownString = ['Công nghệ thông tin', 'Điện tử viễn thông'];