import 'global.dart';

String loginString = lang == 'vi' ? 'Đăng nhập' : 'Sign In';
String signUpString = lang == 'vi' ? 'Đăng ký' : 'Sign Up';
String emailString = 'Email';
String passwordString = lang == 'vi' ? 'Mật khẩu' : 'Password';
String forgetPasswordString = lang == 'vi' ? 'Quên mật khẩu?' : 'Forgot Password?';
String forgotPasswordString = lang == 'vi' ? 'Quên mật khẩu' : 'Forgot Password';
String notHaveAccountString = lang == 'vi' ? 'Chưa có tài khoản?' : 'Don\'t have account';
String registerNowString = lang == 'vi' ? 'Đăng ký ngay' : 'Register now';
String createAccountString = lang =='vi' ? 'Tạo tài khoản' : 'Create Account';
String infoAccountString = lang =='vi' ? 'Thông tin tài khoản' : 'Account Information';
String infoPersonalString = lang =='vi' ? 'Thông tin cá nhân' : 'Personal Information';
String confirmPasswordString = lang == 'vi' ? 'Xác nhận mật khẩu' : 'Confirm Password';
String nextString = lang == 'vi' ? 'Tiếp' : 'Next';
String alreadyHaveAccount = lang == 'vi' ? 'Đã có tài khoản?' : 'Already have account?';
String fullNameString = lang == 'vi' ? 'Họ và Tên' : 'Fullname';
String studentIdString = lang == 'vi' ? 'Mã sinh viên' : 'Student ID';
String classString = lang == 'vi' ? 'Lớp' : 'Class';
String facultyString = lang == 'vi' ? 'Khoa' : 'Faculty';
String enterEmailString = lang == 'vi' ? 'Nhập email của bạn' : 'Enter your email address';
String orString = lang == 'vi' ? 'hoặc' : 'or';
String backToSignInString = lang == 'vi' ? 'Quay về đăng nhập' : 'Back to Sign In';
String sendToEmailString = lang == 'vi' ? 'Gửi tới Email' : 'Send to Email';
String homeString = lang == 'vi' ? 'Trang chủ' : 'Home';
String scheduleString = lang == 'vi' ? 'Lập lịch' : 'Schedule';
String notificationString = lang == 'vi' ? 'Thông báo' : 'Notifications';
String meString = lang == 'vi' ? 'Tôi' : 'Me';
String trainingProgramString = lang == 'vi' ? 'Chương trình đào tạo' : 'Training Programmes';
String recentModuleString = lang == 'vi' ? 'Học phần gần đây' : 'Recent Modules';
String studyProcessString = lang == 'vi' ? 'Tiến trình học tập' : 'Study Process';
String internString = lang == 'vi' ? 'Thực tập' : 'Intern';
String postString = lang == 'vi' ? 'Bài đăng' : 'Post';
String allString = lang == 'vi' ? 'Tất cả' : 'All';
String schoolFacultyString = lang == 'vi' ? 'Trường/ Khoa' : 'School/Faculty';
String companyString = lang == 'vi' ? 'Công ty' : 'Company';
String statisticString = lang == 'vi' ? 'Thống kê' : 'Statistic';
String listPartnerString = lang == 'vi' ? 'DS Đối tác' : 'Partner List';
String reportString = lang == 'vi' ? 'Báo cáo' : 'Report';
String searchString = lang == 'vi' ? 'Tìm kiếm' : 'Search';
String cancelString = lang == 'vi' ? 'Huỷ bỏ' : 'Cancel';
String recentString = lang == 'vi' ? 'Gần đây' : 'Recent';
String shortTrainingProgramString = lang == 'vi' ? 'CTDT' : 'Program';
String moduleString = lang == 'vi' ? 'Học phần' : 'Module';
String lecturerString = lang == 'vi' ? 'Giảng viên' : 'Lecturer';
String partnerString = lang == 'vi' ? 'Đối tác' : 'Partner';
String myProfileString = lang == 'vi' ? 'Hồ sơ cá nhân' : 'My Profile';
String settingString = lang == 'vi' ? 'Cài đặt' : 'Settings';
String shortStudentIdString = lang == 'vi' ? 'MSV' : 'Student ID';
String myCVString = lang == 'vi' ? 'CV của tôi' : 'My CV';
String changePasswordString = lang == 'vi' ? 'Thay đổi mật khẩu' : 'Change Password';
String changePasswordString2 = lang == 'vi' ? 'Đổi mật khẩu' : 'Change Password';
String logOutString = lang == 'vi' ? 'Đăng xuất' : 'Sign Out';
String editProfileString = lang == 'vi' ? 'Chỉnh sửa hồ sơ' : 'Edit Profile';
String dateOfBirthString = lang == 'vi' ? 'Ngày sinh' : 'Birthday';
String languageString = lang == 'vi' ? 'Ngôn ngữ' : 'Language';
String vietnameseString = lang == 'vi' ? 'Tiếng Việt' : 'Vietnamese';
String englishString = lang == 'vi' ? 'Tiếng Anh' : 'English';
String darkModeString = lang == 'vi' ? 'Chế độ tối' : 'Dark Mode';
String onString = lang == 'vi' ? 'Bật' : 'On';
String offString = lang == 'vi' ? 'Tắt' : 'Off';
String doNotDisturbString = lang == 'vi' ? 'Không làm phiền' : 'Do not disturb';
String soundString = lang == 'vi' ? 'Âm báo' : 'Sound';
String oldPasswordString = lang == 'vi' ? 'Mật khẩu cũ' : 'Old Password';
String newPasswordString = lang == 'vi' ? 'Mật khẩu mới' : 'New Password';
String reEnterPasswordString = lang == 'vi' ? 'Nhập lại mật khẩu' : 'Re-enter Password';
String markAllString = lang == 'vi' ? 'Đánh dấu tất cả đã đọc' : 'Mark all as read';
String newString = lang == 'vi' ? 'Mới' : 'New';
String earlierString = lang == 'vi' ? 'Trước đây' : 'Earlier';
String timetableString = lang == 'vi' ? 'Thời gian biểu' : 'Timetable';
String termString = lang == 'vi' ? 'Kì học' : 'Term';
String addTimetableString = lang == 'vi' ? 'Thêm thời gian biểu' : 'Add Timetable';
String classString2 = lang == 'vi' ? 'Lớp học' : 'Class';
String assignmentString = lang == 'vi' ? 'Bài tập' : 'Assignment';
String shortDeadlineString = 'DL';
String categoryString = lang == 'vi' ? 'Loại' : 'Category';
String fromString = lang == 'vi' ? 'Từ' : 'From';
String toString = lang == 'vi' ? 'Đến' : 'To';
String locationString = lang == 'vi' ? 'Địa điểm' : 'Location';
String timeString = lang == 'vi' ? 'Thời gian' : 'Time';
String moduleNameString = lang == 'vi' ? 'Tên học phần' : 'Module Name';
String addString = lang == 'vi' ? 'Thêm' : 'Add';
String addTermString = lang == 'vi' ? 'Thêm kỳ học' : 'Add Term';
String startString = lang == 'vi' ? 'Bắt đầu' : 'Start';
String endString = lang == 'vi' ? 'Kết thúc' : 'End';
String editString = lang == 'vi' ? 'Chỉnh sửa' : 'Edit';
String addModuleString = lang == 'vi' ? 'Thêm môn học' : 'Add Module';
String editModuleString = lang == 'vi' ? 'Chỉnh sửa môn học' : 'Edit Module';
String classesString = lang == 'vi' ? 'Lớp học' : 'Classes';
String lectureString = lang == 'vi' ? 'Lý thuyết' : 'Lecture';
String practicalString = lang == 'vi' ? 'Thực hành' : 'Practical';
String addClassString = lang == 'vi' ? 'Thêm lớp học' : 'Add Class';
String repeatString = lang == 'vi' ? 'Lặp lại' : 'Repeat';
String neverString = lang == 'vi' ? 'Không' : 'Never';
String eachWeekString = lang == 'vi' ? 'Mỗi tuần' : 'Each Week';
String each2WeeksString = lang == 'vi' ? 'Mỗi 2 tuần' : 'Each 2 Weeks';
String eachMonthString = lang == 'vi' ? 'Mỗi tháng' : 'Each Month';
String each2MonthsString = lang == 'vi' ? 'Mỗi 2 tháng' : 'Each 2 Months';
String generalInformationString = lang == 'vi' ? 'Thông tin chung' : 'General Information';
String goalString = lang == 'vi' ? 'Mục tiêu' : 'Goal';
String expectedLearningOutcomeString = lang == 'vi' ? 'Chuẩn đầu ra' : 'Expected Learning Outcome';
String learningProcessString = lang == 'vi' ? 'Tiến trình học' : 'Learning Process';
String trainingProgramNameString = lang == 'vi' ? 'Tên ngành đào tạo' : 'Training Program Name';
String trainingProgramIdString = lang == 'vi' ? 'Mã số ngành đào tạo' : 'Training Program Id';
String trainingTimeString = lang == 'vi' ? 'Thời gian đào tạo' : 'Training Time';
String diplomaString = lang == 'vi' ? 'Tên văn bằng tốt nghiệp' : 'Diploma';
String unitString = lang == 'vi' ? 'Đơn vị' : 'Unit';
String generalGoalString = lang == 'vi' ? 'Mục tiêu chung' : 'General Goal';
String aboutKnowledgeString = lang == 'vi' ? 'Về kiến thức' : 'About Knowledge';
String aboutSkillString = lang == 'vi' ? 'Về kỹ năng' : 'About Skill';
String aboutAttitudeString = lang == 'vi' ? 'Về thái độ' : 'About Attitude';
String specificGoalsString = lang == 'vi' ? 'Các mục tiêu cụ thể' : 'Specific Goals';
String showMoreString = lang == 'vi' ? 'Xem thêm' : 'Show More';
String showLessString = lang == 'vi' ? 'Rút gọn' : 'Show Less';
String totalCreditString = lang == 'vi' ? 'Tổng số tín chỉ' : 'Total number of credits';
String generalKnowledgeBlockString = lang == 'vi' ? 'Khối kiến thức chung' : 'General knowledge block';
String oneKnowledgeBlockString = lang == 'vi' ? 'Khối kiến thức khối ngành' : 'General knowledge block';
String twoKnowledgeBlockString = lang == 'vi' ? 'Khối kiến thức nhóm ngành' : 'General knowledge block';
String creditString = lang == 'vi' ? 'tín chỉ' : 'credit';
String aboutMoralQualityString = lang == 'vi' ? 'Về phẩm chất đạo đức' : 'About moral quality';
String careerPathString = lang == 'vi' ? 'Con đường sự nghiệp' : 'Career Path';
String academicPathString = lang == 'vi' ? 'Con đường học vấn' : 'Academic Path';
String statisticalString = lang == 'vi' ? 'Thống kê' : 'Statistical';
String statisticalChartString = lang == 'vi' ? 'Biểu đồ thống kê' : 'Statistical Chart';
String nextTermModuleString = lang == 'vi' ? 'Học phần kì tới' : 'Next Term\'s Modules';
String finishedCreditShortString = lang == 'vi' ? 'Đã hoàn thành' : 'Finished';
String retakeCreditShortString = lang == 'vi' ? 'Học lại' : 'Retaken';
String unlearnedCreditShortString = lang == 'vi' ? 'Chưa học' : 'Unlearned';
String unFinishedCreditShortString = lang == 'vi' ? 'Chưa hoàn thành' : 'Unfinished';
String onPlanCreditShortString = lang == 'vi' ? 'Dự định' : 'On plan';
String improvableCreditShortString = lang == 'vi' ? 'Cải thiện' : 'Improvable';
String unimprovableCreditShortString = lang == 'vi' ? 'Không thể cải thiện' : 'Unimprovable Credits\'s Number';
String finishedCreditString = lang == 'vi' ? 'Tín chỉ đã hoàn thành' : 'Finished Credits\'s Number';
String retakeCreditString = lang == 'vi' ? 'Tín chỉ học lại' : 'Retaken Credits\'s Number';
String unlearnedCreditString = lang == 'vi' ? 'Tín chỉ chưa học' : 'Unlearned Credits\'s Number';
String unFinishedCreditString = lang == 'vi' ? 'Tín chỉ chưa hoàn thành' : 'Unfinished Credits\'s Number';
String onPlanCreditString = lang == 'vi' ? 'Tín chỉ dự định học' : 'On plan Credits\'s Number';
String improvableCreditString = lang == 'vi' ? 'Tín chỉ có thể cải thiện' : 'Improvable Credits\'s Number';
String unimprovableCreditString = lang == 'vi' ? 'Tín chỉ không thể cải thiện' : 'Unimprovable Credits\'s Number';
String figureForCreditByProgressString = lang == 'vi' ? ' Thống kê tín chỉ theo tiến độ' : 'The figure for credits by progress';
String figureForImprovableCreditString = lang == 'vi' ? ' Thống kê tín chỉ có thể cải thiện' : 'The figure for improvable credits';
String mandatoryModuleString = lang == 'vi' ? 'Học phần bắt buộc' : 'Mandatory Modules';
String optionalModuleString = lang == 'vi' ? 'Học phần tự chọn' : 'Optional Modules';
String supplementaryModuleString = lang == 'vi' ? 'Học phần bổ trợ' : 'Supplementary Modules';
String mandatoryString = lang == 'vi' ? 'Bắt buộc' : 'Mandatory';
String optionalString = lang == 'vi' ? 'Tự chọn' : 'Optional';
String supplementaryString = lang == 'vi' ? 'Bổ trợ' : 'Supplementary';
String personalInformationString = lang == 'vi' ? 'Thông tin cá nhân' : 'Personal Information';
String moduleInChargeString = lang == 'vi' ? 'Học phần phụ trách' : 'Modules In Charge';
String telephoneString = lang == 'vi' ? 'Điện thoại' : 'Telephone';
String faxString = 'Fax';
String contactInformationString = lang == 'vi' ? 'Thông tin liên lạc' : 'Contact Information';
String introductionString = lang == 'vi' ? 'Giới thiệu' : 'Introduction';
String recruitmentPostString = lang == 'vi' ? 'Bài đăng tuyển dụng' : 'Recruitment Posts';
String headOfficeString = lang == 'vi' ? 'Trụ sở chính' : 'Head Office';
String internshipRegisterString = lang == 'vi' ? 'Đăng ký thực tập' : 'Internship\'s Registration';
String partnerCompanyRegistrationString = lang == 'vi' ? 'Đăng ký công ty đối tác' : 'Registration for partner company';
String externalCompanyRegistrationString = lang == 'vi' ? 'Đăng ký công ty ngoài' : 'Registration for external company';
String acceptString = lang == 'vi' ? 'Chấp thuận' : 'Accept';
String inProgressString = lang == 'vi' ? 'Đang xử lý' : 'In Progress';
String declineString = lang == 'vi' ? 'Từ chối' : 'Decline';
String companyNameString = lang == 'vi' ? 'Tên công ty' : 'Company \'s Name';
String emailContactString = lang == 'vi' ? 'Email liên hệ' : 'Email Contact';
String phoneNumberContactString = lang == 'vi' ? 'SĐT liên hệ' : 'Phone Number Contact';
String internshipFieldString = lang == 'vi' ? 'Lĩnh vực thực tập' : 'Internship Field';
String partnerListString = lang == 'vi' ? 'Danh sách đối tác' : 'Partner List';
String websiteString = 'Website';
String recruitingString = lang == 'vi' ? 'Đang tuyển' : 'Recruiting';
String internshipReportString = lang == 'vi' ? 'Báo cáo thực tập' : 'Internship Report';
String internshipInformationString = lang == 'vi' ? 'Thông tin thực tập' : 'Internship Information';
String submitReportString = lang == 'vi' ? 'Nộp báo cáo' : 'Submit report';
String resultString = lang == 'vi' ? 'Kết quả' : 'Result';
String internshipTypeString = lang == 'vi' ? 'Loại thực tập' : 'Internship Type';
String internshipCompanyString = lang == 'vi' ? 'Công ty thực tập' : 'Internship Company';
String replaceString = lang == 'vi' ? 'Thay thế' : 'Replace';
String pointString = lang == 'vi' ? 'Điểm' : 'Point';
String contactString = lang == 'vi'? 'Liên hệ' : 'Contact';
String postedDateString = lang == 'vi'? 'Ngày đăng' : 'Posted Date';
String expiredDateString = lang == 'vi'? 'Ngày hết hạn' : 'Expired Date';


List<String> classDropDownString = ['K64C-CLC', 'K64C-B'];
List<String> facultyDropDownString = ['Công nghệ thông tin', 'Điện tử viễn thông'];
List<String> classTypeDropDownString = [lectureString, practicalString];
List<String> repeatClassDropDownString = [neverString, eachWeekString, each2WeeksString, eachMonthString, each2MonthsString];
List<String> categoryDropDownString = [classString2, assignmentString];
List<String> daysOfWeek = [
  lang == 'vi' ? 'Thứ hai' : 'Monday',
  lang == 'vi' ? 'Thứ ba' : 'Tuesday',
  lang == 'vi' ? 'Thứ tư' : 'Wednesday',
  lang == 'vi' ? 'Thứ năm' : 'Thursday',
  lang == 'vi' ? 'Thứ sáu' : 'Friday',
  lang == 'vi' ? 'Thứ bảy' : 'Saturday',
  lang == 'vi' ? 'Chủ nhật' : 'Sunday',
];